In [2]:
import pandas as pd
import geopandas
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#stream directy from github
import requests
import csv

#Get Continent name
import pycountry_convert as pc
import pycountry

from datetime import datetime

#Get coordinates
from geopy.geocoders import Nominatim

#For mapping
from shapely.geometry import Polygon

#Disable Warning in cell 6
pd.options.mode.chained_assignment = None

In [3]:
URL = 'https://covid.ourworldindata.org/data/owid-covid-data.csv'

with requests.Session() as s:
    download = s.get(URL)
    decoded_content = download.content.decode('utf-8')
    
    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = list(cr)

In [4]:
df_new = pd.DataFrame(my_list, columns=my_list[0]).drop([0])
df_new.iloc[50:100,:]

,iso_code,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,total_deaths_per_million,...,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cvd_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_100k
51,ABW,Aruba,2020-05-12,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
52,ABW,Aruba,2020-05-13,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
53,ABW,Aruba,2020-05-14,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
54,ABW,Aruba,2020-05-15,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
55,ABW,Aruba,2020-05-16,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
56,ABW,Aruba,2020-05-17,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
57,ABW,Aruba,2020-05-18,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
58,ABW,Aruba,2020-05-19,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
59,ABW,Aruba,2020-05-20,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
60,ABW,Aruba,2020-05-21,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
61,ABW,Aruba,2020-05-22,101,0,3,0,945.994,0.0,28.099,...,13.085,7.452,35973.781,,,11.62,,,,
62,AFG,Afghanistan,2019-12-31,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
63,AFG,Afghanistan,2020-01-01,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
64,AFG,Afghanistan,2020-01-02,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
65,AFG,Afghanistan,2020-01-03,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
66,AFG,Afghanistan,2020-01-04,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
67,AFG,Afghanistan,2020-01-05,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
68,AFG,Afghanistan,2020-01-06,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
69,AFG,Afghanistan,2020-01-07,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
70,AFG,Afghanistan,2020-01-08,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
71,AFG,Afghanistan,2020-01-09,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
72,AFG,Afghanistan,2020-01-10,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
73,AFG,Afghanistan,2020-01-11,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
74,AFG,Afghanistan,2020-01-12,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
75,AFG,Afghanistan,2020-01-13,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
76,AFG,Afghanistan,2020-01-14,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
77,AFG,Afghanistan,2020-01-15,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
78,AFG,Afghanistan,2020-01-16,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
79,AFG,Afghanistan,2020-01-17,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
80,AFG,Afghanistan,2020-01-18,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
81,AFG,Afghanistan,2020-01-19,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
82,AFG,Afghanistan,2020-01-20,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
83,AFG,Afghanistan,2020-01-21,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
84,AFG,Afghanistan,2020-01-22,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
85,AFG,Afghanistan,2020-01-23,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
86,AFG,Afghanistan,2020-01-24,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
87,AFG,Afghanistan,2020-01-25,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
88,AFG,Afghanistan,2020-01-26,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
89,AFG,Afghanistan,2020-01-27,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
90,AFG,Afghanistan,2020-01-28,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
91,AFG,Afghanistan,2020-01-29,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
92,AFG,Afghanistan,2020-01-30,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
93,AFG,Afghanistan,2020-01-31,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
94,AFG,Afghanistan,2020-02-01,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
95,AFG,Afghanistan,2020-02-02,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
96,AFG,Afghanistan,2020-02-03,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
97,AFG,Afghanistan,2020-02-04,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
98,AFG,Afghanistan,2020-02-05,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
99,AFG,Afghanistan,2020-02-06,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5
100,AFG,Afghanistan,2020-02-07,0,0,0,0,0.0,0.0,0.0,...,2.581,1.337,1803.987,,597.029,9.59,,,37.746,0.5

In [5]:
#Add continent column - this results in errors because country name differentiate
to_country_code = lambda row: pc.country_name_to_country_alpha2(row, cn_name_format="default")
try:
    country_code = new_df['location'].apply(to_country_code)
except:
    NameError

In [6]:
#Rename some countries to work

#Côte d'Ivoire
location_ivory_coast = df_new.location[df_new.location == "Cote d'Ivoire"]
df_new.location[df_new.location == "Cote d'Ivoire"] = location_ivory_coast.replace(to_replace = "Cote d'Ivoire",value="Côte d'Ivoire")

#Faroe Islands
location_faroe_islands = df_new.location[df_new.location == "Faeroe Islands"]
df_new.location[df_new.location == "Faeroe Islands"] = location_faroe_islands.replace(to_replace = "Faeroe Islands",value="Faroe Islands")

#Democratic Republic of the Congo
location_drc = df_new.location[df_new.location == "Democratic Republic of Congo"]
df_new.location[df_new.location == "Democratic Republic of Congo"] = location_drc.replace(to_replace = "Democratic Republic of Congo",value="Democratic Republic of the Congo")

#Curaçao
location_curacao = df_new.location[df_new.location == "Curacao"]
df_new.location[df_new.location == "Curacao"] = location_curacao.replace(to_replace = "Curacao",value="Curaçao")


#Reset Timor to Timor-Leste (proper name)
location_timor = df_new.location[df_new.location == "Timor"]
df_new.location[df_new.location == "Timor"] = location_timor.replace(to_replace = "Timor",value="Timor-Leste")

In [7]:
def create_continent():
    
    '''
    Input: None
    Output: Complete series with continent names
    '''
    #Initializes new Series
    conti_column = pd.Series([],dtype='object')

    continents = {
        'NA': 'North America',
        'SA': 'South America', 
        'AS': 'Asia',
        'OC': 'Australia',
        'AF': 'Africa',
        'EU': 'Europe'}
    
    #Checks which countries have problems using when converting from the 2 country
    #code to continent name, adds these countries to a set
    stuck_alpha2 = set()
    for row in df_new['location']:
        try:
            continents[pc.country_alpha2_to_continent_code(pc.country_name_to_country_alpha2(row))]
        except:
            stuck_alpha2.add(row)

            
            
    
    #Fills in continent name for countries without converting problems and leaves the
    #others as np.nan
    for index,country in enumerate(df_new.location):
        if country in set(df_new.location[~df_new['location'].isin(list(stuck_alpha2))]):
            conti_column.loc[index] = continents[pc.country_alpha2_to_continent_code(pc.country_name_to_country_alpha2(country))]
        else:
            conti_column.loc[index] = np.nan
            
    return conti_column

    #Manually add Continent names for the stuck_alpha2 countries


df_new['continent'] = create_continent()

In [8]:
#Here display the countries that return errors
continents = {
        'NA': 'North America',
        'SA': 'South America', 
        'AS': 'Asia',
        'OC': 'Australia',
        'AF': 'Africa',
        'EU': 'Europe'}

stuck_alpha2 = set()
for row in df_new['location']:
    try:
        continents[pc.country_alpha2_to_continent_code(pc.country_name_to_country_alpha2(row))]
    except:
        stuck_alpha2.add(row)
stuck_alpha2

{'Bonaire Sint Eustatius and Saba',
 'International',
 'Kosovo',
 'Sint Maarten (Dutch part)',
 'Timor-Leste',
 'Vatican',
 'Western Sahara',
 'World'}

In [9]:
#lets change continent values of the stuck alpha2 rows
df_new['continent'][df_new.location == "Bonaire Sint Eustatius and Saba"] = "North America"
df_new['continent'][df_new.location == "Vatican"] = "Europe"
df_new['continent'][df_new.location == "Sint Maarten (Dutch part)"] = "North America"
df_new['continent'][df_new.location == "Timor-Leste"] = "Asia"
df_new['continent'][df_new.location == "Kosovo"] = "Europe"
df_new['continent'][df_new.location == "Western Sahara"] = "Africa"

In [10]:
def create_alpha2():
    alpha2_column = pd.Series(dtype='object')
    
    for index, alpha3 in enumerate(df_new.iso_code):
        try:
            alpha2_column.loc[index] = pc.country_alpha3_to_country_alpha2(alpha3)
        #The only country that appeared to have a error converting is Kosovo
        except:
            if alpha3 == 'RKS':
                alpha2_column.loc[index] = 'XK'
    
    return alpha2_column

df_new['alpha2'] = create_alpha2()

In [11]:
#Here the countries that have nan entries for continent name
continent_nan = df_new[(df_new['continent'].isna())
                & (df_new['location'] != 'World')
                & (df_new['location'] != 'International')]

'''for row in continent_nan.index:
    try:
        change_alpha = pc.country_name_to_country_alpha2(df_new.iloc[row].location)
        #change alpha2
        df_new.iloc[row].alpha2 = change_alpha
        #set continent name
        df_new.iloc[index].continent = pc.country_alpha2_to_continent_code(df_new.iloc[index].alpha2)
    except:
        print (df_new.iloc[row].location)'''

'for row in continent_nan.index:\n    try:\n        change_alpha = pc.country_name_to_country_alpha2(df_new.iloc[row].location)\n        #change alpha2\n        df_new.iloc[row].alpha2 = change_alpha\n        #set continent name\n        df_new.iloc[index].continent = pc.country_alpha2_to_continent_code(df_new.iloc[index].alpha2)\n    except:\n        print (df_new.iloc[row].location)'

In [12]:
#Check for nan Values
continent_nan.isna().sum().continent

7

In [13]:
#Get coordinates
def create_coordinates(column):
    
    geolocator = Nominatim(user_agent="Get_Coordinates")
    #Dict with country key and coordinates value
    #country_coordinates_dict = dict()
    country_latitude_dict = dict()
    country_longitude_dict = dict()
    
    for i in column.unique():
        try:
            loc = geolocator.geocode(i)
            #country_coordinates_dict[i] = [loc.latitude, loc.longitude]
            country_latitude_dict[i] = loc.latitude
            country_longitude_dict[i] = loc.longitude
        except:
            #"Swaziland" to "eSwatini"
            #"Sint Maarten (Dutch part)" to "Sint Maarten"
            if  i == "Sint Maarten (Dutch part)":
                loc_error1 = geolocator.geocode('Sint Maarten')
                #country_coordinates_dict[i] = (loc_error1.latitude, loc_error1.longitude)
                country_latitude_dict[i] = loc_error1.latitude
                country_longitude_dict[i] = loc_error1.longitude
            elif i == "Swaziland":
                loc_error2 = geolocator.geocode('eSwatini')
                #country_coordinates_dict[i] = (loc_error2.latitude, loc_error2.longitude)
                country_latitude_dict[i] = loc_error2.latitude
                country_longitude_dict[i] = loc_error2.longitude
    return country_latitude_dict, country_longitude_dict

In [ ]:
#create new lat,long columns
df_new['latitude'] = df_new['location'].map(create_coordinates(df_new.location)[0])
df_new['longitude'] = df_new['location'].map(create_coordinates(df_new.location)[1])

In [ ]:
#Use the preloaded world dataframe to get geodata for maps
world = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
world.head()

In [ ]:
#edit wrong columns
#france has -99 as its iso_a3 code
world.iso_a3[world.name == 'France'] = 'FRA'
world.iso_a3[world.name == 'Norway'] = 'NOR'

#set index of world and df_new dataframes
set_index_df = df_new.set_index('iso_code')
set_index_world = world.set_index('iso_a3')

#set new dataframe that joins both df's
df = set_index_world.join(set_index_df, lsuffix = '_other').reset_index()
df = df.drop(['index', 'pop_est', 'continent_other', 'name', 'gdp_md_est'],axis=1)

In [ ]:
df.info()

In [ ]:
#make date variable of datetime attribute
df['date'] = pd.to_datetime(df.date,format = '%Y/%m/%d')

In [ ]:
#convert columns to float
cols_to_int = ['total_cases', 'new_cases',
       'total_deaths', 'new_deaths', 'total_cases_per_million',
       'new_cases_per_million', 'total_deaths_per_million',
       'new_deaths_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cvd_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_100k']
for i in cols_to_int:
    df[i] = pd.to_numeric(df[i],downcast='float')

In [ ]:
df.info()

In [ ]:
total_cases_country = df.groupby('location').total_cases.max()
country_gdp = df.groupby('location').gdp_per_capita.mean()

fig, arr_ax = plt.subplots(3, figsize=(10,10))

arr_ax[0].scatter(country_gdp,total_cases_country)
arr_ax[0].set_title("GDP per capita vs number of cases")
arr_ax[1].scatter(x=country_gdp,y=total_cases_country)
arr_ax[1].set_title("GDP per capita vs number of cases log(10)")
plt.yscale("log")

plt.show();

In [ ]:
#create pandas series that matches country to continent  
continent_dict = dict()
for country in df.groupby('location'):
    continent_dict[country[0]] = country[1].continent.unique()[0]
country2continent = pd.Series(continent_dict)

#create pandas series that matches country to its population  
population_dict = dict()
for country in df.groupby('location'):
    population_dict[country[0]] = country[1].population.unique()[0]
country2population = pd.Series(population_dict)

#create pandas series that matches country to its population  
geo_dict = dict()
for country in df.groupby('location'):
    geo_dict[country[0]] = country[1].geometry.unique()[0]
country2geometry = geopandas.GeoSeries(geo_dict)

In [ ]:
#create df to put all above data together
continent_df = pd.concat([total_cases_country,country_gdp],axis=1)
continent_df['continent'] = country2continent
continent_df['population'] = country2population
#continent_df['geometry'] = country2geometry
continent_df.head()

In [ ]:
fig, ax = plt.subplots(figsize = (10,10))

#color of dots
color = {'Africa':'red',
         'Asia':'blue',
         'Europe':'green',
         'North America':'black',
         'Australia':'yellow',
         'South America':'purple'}

# plot scatter plot
grouped = continent_df.reset_index().groupby('continent')
for key, group in grouped:
    group.plot(ax=ax,
                kind='scatter',
                x='gdp_per_capita',
                y='total_cases',
                label=key,
                color=color[key],
                alpha = 0.5,
                s =25)
plt.yscale("log")

plt.title("Log plot: GDP per capita vs cases of COVID-19")
plt.legend()
plt.show()

In [ ]:
#Above graph with population as dot size

In [ ]:
#create geodataframe to make chloropleth map
total_cases_df = geopandas.GeoDataFrame(pd.concat([continent_df, country2geometry.rename('geometry')], axis=1))

In [ ]:
# set the range for the choropleth
vmin, vmax = 1000, 500000
# create figure and axes for Matplotlib
fig, ax = plt.subplots(1, figsize=(20, 8))

total_cases_df.plot(column='total_cases',
                    cmap='Reds',
                    linewidth=0.8,
                    ax=ax,
                    edgecolor='0.8',
                    vmin=vmin,
                    vmax=vmax)
ax.set_title("Total Coronavirus cases")

# Create colorbar as a legend
sm = plt.cm.ScalarMappable(cmap='Reds', norm=plt.Normalize(vmin=vmin, vmax=vmax))
# empty array for the data range
sm._A = []
# add the colorbar to the figure
cbar = fig.colorbar(sm)

plt.show();

In [ ]:
df

In [ ]:
cont_date = df.groupby(['continent','date']).sum().reset_index()
today_date = cont_date[cont_date.date == pd.to_datetime(datetime.strftime(datetime.now(),format = '%Y-%m-%d'))].index

#updated dataframe without todays date included
cont_date = cont_date.drop(today_date)

fig, ax = plt.subplots(2, figsize=(20, 10))

for continent in cont_date.continent.unique():
    ax[0].plot(cont_date[cont_date.continent ==continent]['date'],
            cont_date[cont_date.continent ==continent]['total_cases'],label = continent)
    ax[1].plot(cont_date[cont_date.continent ==continent]['date'],
            cont_date[cont_date.continent ==continent]['new_cases'],label = continent)

fig.suptitle('Cases per continent over Time',fontsize=20)
ax[1].set_xlabel("Date")
ax[1].set_ylabel("Cases")
    
ax[0].legend()
plt.show()

In [ ]:
countries_to_plot = ['United States',
                     'Italy',
                     'Spain',
                     'Brazil',
                     'United Kingdom',
                     'China']

fig, ax = plt.subplots(1,figsize=(20,20))

for country in range(len(countries_to_plot)):
    plot_date = df['date'][df.location == countries_to_plot[country]]
    plot_cases = df['total_cases_per_million'][df.location == countries_to_plot[country]]
    plot_deaths = df['total_deaths_per_million'][df.location == countries_to_plot[country]]
    
    ax.plot(plot_date,plot_cases,
             label=countries_to_plot[country],
             linewidth=3)
    ax.set_ylabel('Cases per Million',fontsize=20)
    ax.set_xlabel('Date',fontsize=20)
    
    

ax.legend()
plt.show()

In [ ]:
'''countries_to_plot = ['United States',
                     'Italy',
                     'Spain',
                     'Brazil',
                     'United Kingdom',
                     'China']

fig, ax = plt.subplots(1,figsize=(20,20))

for country in range(len(countries_to_plot)):    
    plot_date = df['date'][df.location == countries_to_plot[country]]
    plot_deaths = df['total_deaths_per_million'][df.location == countries_to_plot[country]]
    
    ax2=ax.twinx()
    ax2.plot(plot_date,plot_deaths,
             label=countries_to_plot[country],
             linewidth=3)
    #ax2.set_ylabel('Deaths per Million',fontsize=20)
    

plt.legend()
plt.show()'''

In [ ]:
group_country = df.groupby(['date','location']).sum().reset_index()

#select 20 countries with the highest rate of people over 70
countries_top70 = df.groupby(['location','aged_70_older']).sum().reset_index()[['location','aged_70_older']].sort_values('aged_70_older',ascending=False)[0:25].location

fig, ax = plt.subplots(1, figsize=(20,20))

for country in group_country.location.unique():
    ax.plot(group_country['date'][group_country.location == country],
            group_country['total_cases'][group_country.location == country],
            c='grey',
            alpha=0.4)

    
for country in group_country.location.unique():
    if country in list(countries_top70):
        ax.plot(group_country['date'][group_country.location == country],
                group_country['total_cases'][group_country.location == country],
                c='orange',
                alpha=1,
                linewidth=3)
        
ax.set_ylim(0,300000)
plt.show()

In [ ]:
df.groupby('location').mean()['hospital_beds_per_100k']

In [ ]:
df.columns

In [ ]:
plt.scatter(df.groupby('location').mean()['hospital_beds_per_100k'], df.groupby('location').sum()['total_deaths_per_million'])
plt.show()

In [ ]:
plt.scatter(df.groupby('location').mean()['handwashing_facilities'], df.groupby('location').sum()['total_deaths_per_million'])
plt.show()

In [ ]:
df.columns

In [ ]:
fig,ax = plt.subplots(2,figsize=(20,20))

groupby_today = df.groupby('date').sum()

#plot on ax one
ax[0].plot(groupby_today.index, groupby_today['new_cases'], label='New cases per day')
ax[0].plot(groupby_today.index, groupby_today['new_tests'], label='New test per day')
#plot on ax two
ax[1].plot(groupby_today.index, groupby_today['new_cases']*1/1000, label='New cases per day')
ax[1].plot(groupby_today.index, groupby_today['new_tests'], label='New test per day')


ax[0].set_xlim(groupby_today.index[0],groupby_today.index[-3])
ax[0].set_title("Number of tests vs cases")

ax[1].set_xlim(groupby_today.index[0],groupby_today.index[-3])
ax[1].set_title("Number of tests vs cases")

ax[0].legend()
ax[1].legend()

ax[1].set_yscale("log")
plt.show()

In [ ]:
#https://python-graph-gallery.com/163-donut-plot-with-subgroups/
#create nested pie chart

group_continent = df.groupby(['date','continent']).sum().reset_index()
#main continent cases - using iloc here because ocasionally the most recent value is skew
namerica_total = group_continent.total_cases[group_continent.continent == 'North America'].iloc[-2]
europe_total = group_continent.total_cases[group_continent.continent == 'Europe'].iloc[-2]
asia_total = group_continent.total_cases[group_continent.continent == 'Asia'].iloc[-2]
#other cases
samerica_total = group_continent.total_cases[group_continent.continent == 'South America'].iloc[-2]
africa_total = group_continent.total_cases[group_continent.continent == 'Africa'].iloc[-2]
australia_total = group_continent.total_cases[group_continent.continent == 'Australia'].iloc[-2]

#plot certain countries
us_total = max(df[(df.location == "United States")].total_cases)

russia_total = max(df[(df.location == "Russia")].total_cases)
spain_total = max(df[(df.location == "Spain")].total_cases)
uk_total = max(df[(df.location == "United Kingdom")].total_cases)
italy_total = max(df[(df.location == "Italy")].total_cases)
france_total = max(df[(df.location == "France")].total_cases)
germany_total = max(df[(df.location == "Germany")].total_cases)

turkey_total = max(df[(df.location == "Turkey")].total_cases)
india_total = max(df[(df.location == "India")].total_cases)
iran_total = max(df[(df.location == "Iran")].total_cases)
china_total = max(df[(df.location == "China")].total_cases)

brazil_total = max(df[(df.location == "Brazil")].total_cases)


#set for pie chart
group_names = ['North America','Europe','Asia','Others']
group_size = [namerica_total, europe_total, asia_total, samerica_total+africa_total+australia_total]
subgroup_names = ["USA", "",
                  "Russia", "Spain", "UK", "Italy", "France", "Germany", "",
                  "Turkey", "India", "Iran", "China", "",
                  "Brazil", ""]
subgroup_size = [us_total, namerica_total-us_total, 
                  russia_total, spain_total, uk_total, italy_total, france_total, germany_total, europe_total-spain_total-uk_total-russia_total-italy_total-france_total-germany_total, 
                  turkey_total, india_total, iran_total, china_total, asia_total-india_total-turkey_total-iran_total-china_total, 
                  brazil_total, samerica_total+africa_total+australia_total - brazil_total]

# Create colors
a, b, c, d = [plt.cm.Blues, plt.cm.Reds, plt.cm.Greens, plt.cm.Greys]
 
# First Ring (outside)
fig, ax = plt.subplots(figsize=(10,10))
ax.axis('equal')
mypie, _ = ax.pie(group_size, radius=1.6, labels=group_names, colors=[a(0.8), b(0.8), c(0.8), d(0.5)] )
#plt.setp( mypie, width=0.3, edgecolor='white')
 
# Second Ring (Inside)
mypie2, _ = ax.pie(subgroup_size,
                   radius=1.6-0.3,
                   labels=subgroup_names,
                   labeldistance=0.7,
                   colors=[a(0.7), a(0.6), b(0.7), b(0.6), b(0.5), b(0.4), b(0.3), b(0.2), b(0.1), c(0.7), c(0.6), c(0.5), c(0.4), c(0.3), d(0.3), d(0.2)])
#plt.setp( mypie2, width=0.4, edgecolor='white')
plt.margins(0,0)

In [ ]:
#check where the nan values are
df.groupby('location').mean().isna().mean()

In [ ]:
#create heatmap to show correlations

plt.figure(figsize=(20,20))

Var_Corr = df.corr()
# plot the heatmap and annotation on it
sns.heatmap(Var_Corr, xticklabels=Var_Corr.columns, yticklabels=Var_Corr.columns, annot=True)

In [ ]:
#make train/test data
#make list and randomly add to list for training data

In [ ]:
from sklearn.linear_model import LinearRegression


X = df.groupby('location').mean()[['hospital_beds_per_100k', 'population_density', 'median_age',
       'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cvd_death_rate', 'diabetes_prevalence']]
y = df.groupby('location').sum()['total_cases']

reg = LinearRegression().fit(X,y)

In [ ]:
df.groupby('location').mean()

Wont include handwashing facilities, and male/female smokers.

In [ ]:
df

In [ ]:
continent_df

In [ ]:
#groupby location and then resample by week - get new cases
test = df.set_index('date').groupby(['location']).resample("W").sum().reset_index()[['location','date','new_cases']]

In [ ]:
for date in test['date'].unique():
    print (date)

In [ ]:
#groupby location and then resample by week - get new cases
df.set_index('date').groupby(['location']).resample("M").sum().reset_index()[['date','new_cases']]

In [ ]:
fig, ax = plt.subplots(figsize = (10,10))

#color of dots
color = {'Africa':'red',
         'Asia':'blue',
         'Europe':'green',
         'North America':'black',
         'Australia':'yellow',
         'South America':'purple'}

# plot scatter plot
grouped = continent_df.reset_index().groupby('population')
for key, group in grouped:
    group.plot(ax=ax,
                kind='scatter',
                x='gdp_per_capita',
                y='total_cases',
                #label=key,
                #color=color[key],
                alpha = 0.5,
                s = key/1000000)
plt.yscale("log")

plt.title("Log plot: GDP per capita vs cases of COVID-19")
plt.show()

In [ ]:
grouped = continent_df.reset_index().groupby(['continent','location','population'])
for key, group in grouped:
    print (key)

In [ ]:
#color of dots
fig, ax = plt.subplots(figsize = (10,10))

color = {'Africa':'red',
         'Asia':'blue',
         'Europe':'green',
         'North America':'black',
         'Australia':'yellow',
         'South America':'purple'}

grouped = continent_df.reset_index().groupby(['continent','population'])

continent_used = []
for key, group in grouped:
    if key[0] not in continent_used:
        plt.scatter(x=group['gdp_per_capita'],
                    y=group['total_cases'],
                    label=key[0],
                    color=color[key[0]],
                    alpha = 0.5,
                    s = key[1]/1000000)
        continent_used.append(key[0])
    else:
        plt.scatter(x=group['gdp_per_capita'],
                    y=group['total_cases'],
                    #label=key[0],
                    color=color[key[0]],
                    alpha = 0.5,
                    s = key[1]/1000000
              )
plt.yscale("log")

plt.legend()
plt.show()

In [ ]:
import matplotlib.animation as animation

fig, ax = plt.subplots(figsize = (10,10))

#color of dots
color = {'Africa':'red',
         'Asia':'blue',
         'Europe':'green',
         'North America':'black',
         'Australia':'yellow',
         'South America':'purple'}

# plot scatter plot
grouped = continent_df.reset_index().groupby('continent')
for key, group in grouped:
    group.plot(ax=ax,
                kind='scatter',
                x='gdp_per_capita',
                y='total_cases',
                label=key,
                color=color[key],
                alpha = 0.5,
                s =25)
plt.yscale("log")

plt.title("Log plot: GDP per capita vs cases of COVID-19")

'''def update(frame_number):
    # Get an index which we can use to re-spawn the oldest raindrop.
    current_index = frame_number % n_drops

    # Make all circles bigger.
    rain_drops['size'] += rain_drops['growth']

    # Pick a new position for oldest rain drop, resetting its size,
    # color and growth factor.
    rain_drops['position'][current_index] = np.random.uniform(0, 1, 2)
    rain_drops['size'][current_index] = 5
    rain_drops['color'][current_index] = (0, 0, 0, 1)
    rain_drops['growth'][current_index] = np.random.uniform(50, 200)

    # Update the scatter collection, with the new colors, sizes and positions.
    scat.set_edgecolors(rain_drops['color'])
    scat.set_sizes(rain_drops['size'])
    scat.set_offsets(rain_drops['position'])


# Construct the animation, using the update function as the animation director.
animation = FuncAnimation(fig, update, interval=10)'''

plt.legend()
plt.show()

In [ ]:
#Create median age bins
to_sort = df.groupby('location').mean()['median_age']
bins = [0,20,30,40,50]

age_bins = pd.cut(to_sort,bins,labels = ['<20','20-30','30-40','40-50'])

In [ ]:
#New age bin column
to_bin = lambda x: age_bins[x]
df['age_bins'] = df.location[df.location.notna()].apply(to_bin).astype(str)
df['age_bins'] = df['age_bins'].astype(str)

df['age_bins'].unique()

In [ ]:
df['age_bins'].value_counts()

In [ ]:
#make df that is first grouped by country and age group
country_age = df.groupby(['location','age_bins'])[['total_cases','total_deaths']].max().reset_index()
#set the order in which the bars should appear
cases_age = country_age.groupby('age_bins').sum().reindex(['<20', '20-30', '30-40','40-50']).reset_index()

#bars for the whole world
plt.bar(cases_age['age_bins'],
        cases_age['total_cases'],
        label='Rest of the World')

#bars for the US
plt.bar(country_age['age_bins'][(country_age['age_bins'] != 'nan') & (country_age['location'] == 'United States')],
        country_age['total_cases'][(country_age['age_bins'] != 'nan') & (country_age['location'] == 'United States')],
        label='United States')

plt.title("Cases in countries by median age group")
plt.xlabel('Median age group')
plt.ylabel('Cases')

plt.legend()
plt.show()

Now create whole new map

In [ ]:
#function to return cartesian coordinates
#https://stackoverflow.com/questions/1185408/converting-from-longitude-latitude-to-cartesian-coordinates
def spherical_to_cartesian(lat,long):

    R = 1 #radius of the earth = 6367 km

    x = R * np.cos((lat)/180 *np.pi) * np.cos((long)/180 *np.pi)
    y = R * np.cos((lat)/180 *np.pi) * np.sin((long)/180 *np.pi)
    z = R *np.sin((lat)/180 *np.pi)

    return x,y,z

In [ ]:
#create new x, y and z cartesian columns
df['x'] = spherical_to_cartesian(df['latitude'],df['longitude'])[0]
df['y'] = spherical_to_cartesian(df['latitude'],df['longitude'])[1]
df['z'] = spherical_to_cartesian(df['latitude'],df['longitude'])[2]

In [ ]:
#groupby location and then resample by week - get new cases
country_cases_week = df.set_index('date').groupby(['location']).resample("M").sum().reset_index()[['date','new_cases']]

In [ ]:
#groupby location and then resample by week - get cardinal
country_cardinal_week = df.set_index('date').groupby(['location']).resample("M").mean().reset_index()[['x','y','z']]

In [ ]:
location_weighted_df = pd.concat([country_cases_week,country_cardinal_week],axis=1)

In [ ]:
#Create weighted mean
def wm(x):
    try:
        return np.average(x, weights=location_weighted_df.loc[x.index, "new_cases"])
    except ZeroDivisionError:
        return 0 
    
weighted_df = location_weighted_df.groupby('date').agg(x_weighted_mean=("x", wm),
                                         y_weighted_mean=("y", wm),
                                         z_weighted_mean=("z", wm))

In [ ]:
#function to return spherical coordinates
#https://stackoverflow.com/questions/1185408/converting-from-longitude-latitude-to-cartesian-coordinates
def cartesian_to_spherical(x,y,z):
    
    R = 1 #radius of the earth = 6367 km
    
    latitude = np.arcsin(z / R)
    longitude = np.arctan2(y, x)
    
    #convert from radians to degrees
    latitude = (latitude/np.pi)*180
    longitude = (longitude/np.pi)*180
    
    return latitude, longitude

In [ ]:
weighted_df['latitude'] = cartesian_to_spherical(weighted_df['x_weighted_mean'],
                           weighted_df['y_weighted_mean'],
                           weighted_df['z_weighted_mean'])[0]
weighted_df['longitude'] = cartesian_to_spherical(weighted_df['x_weighted_mean'],
                           weighted_df['y_weighted_mean'],
                           weighted_df['z_weighted_mean'])[1]

In [ ]:
#make data more versatile by adding new_cases
weighted_df = pd.concat([weighted_df,location_weighted_df.groupby('date').sum()],axis=1)

In [ ]:
weighted_df

In [ ]:
weighted_df.loc['2020-03-31'].longitude-10

In [ ]:
#plot movement of COVID-19 across the world
#https://geopandas.readthedocs.io/en/latest/gallery/create_geopandas_from_pandas.html


#plot world
ax = world.plot(color='white', edgecolor='black', figsize = (20,20))

#plot data
plt.scatter(weighted_df.longitude,
            weighted_df.latitude,
            color='red',
            s=weighted_df.new_cases/5000,
            alpha =0.9)
plt.plot(weighted_df.longitude,
            weighted_df.latitude,
            color ='red',
            linewidth=3)

#plt.xlim(10,150)
#plt.ylim(-20,60)



plt.annotate("March",
             (weighted_df.loc['2020-03-31'].longitude, weighted_df.loc['2020-03-31'].latitude),
             (weighted_df.loc['2020-03-31'].longitude  - 20, weighted_df.loc['2020-03-31'].latitude + 5),
             fontsize=20,
             color='red')
plt.annotate("April",
             (weighted_df.loc['2020-04-30'].latitude,weighted_df.loc['2020-04-30'].latitude),
             (weighted_df.loc['2020-04-30'].longitude  - 20, weighted_df.loc['2020-04-30'].latitude + 2),
             fontsize=20,
             color='red')
plt.annotate("May",
             (weighted_df.loc['2020-05-31'].longitude,weighted_df.loc['2020-05-31'].latitude),
             (weighted_df.loc['2020-05-31'].longitude - 20,weighted_df.loc['2020-05-31'].latitude - 1),
             fontsize=20,
             color='red')

plt.title("The geographic center of COVID-19 over time", fontsize = 30)

plt.axis('off')
plt.show()

In [ ]:
# set the range for the choropleth
vmin, vmax = 1000, 500000
# create figure and axes for Matplotlib
fig, ax = plt.subplots(1, figsize=(30, 12))

total_cases_df.plot(column='total_cases',
                    cmap='Reds',
                    linewidth=0.8,
                    ax=ax,
                    edgecolor='0.8',
                    vmin=vmin,
                    vmax=vmax,figsize=(30,20))
ax.set_title("Total Coronavirus cases")

# Create colorbar as a legend
sm = plt.cm.ScalarMappable(cmap='Reds', norm=plt.Normalize(vmin=vmin, vmax=vmax))
# empty array for the data range
sm._A = []
# add the colorbar to the figure
cbar = fig.colorbar(sm)


#plot data
plt.scatter(weighted_df.longitude,
            weighted_df.latitude,
            color='red',
            s=weighted_df.new_cases/5000,
            alpha =0.9)
plt.plot(weighted_df.longitude,
            weighted_df.latitude,
            color ='red',
            linewidth=3)
#annote the points
plt.annotate("March",
             (weighted_df.loc['2020-03-31'].longitude, weighted_df.loc['2020-03-31'].latitude),
             (weighted_df.loc['2020-03-31'].longitude  - 20, weighted_df.loc['2020-03-31'].latitude + 5),
             fontsize=20,
             color='red')
plt.annotate("April",
             (weighted_df.loc['2020-04-30'].latitude,weighted_df.loc['2020-04-30'].latitude),
             (weighted_df.loc['2020-04-30'].longitude  - 20, weighted_df.loc['2020-04-30'].latitude + 2),
             fontsize=20,
             color='red')
plt.annotate("May",
             (weighted_df.loc['2020-05-31'].longitude,weighted_df.loc['2020-05-31'].latitude),
             (weighted_df.loc['2020-05-31'].longitude - 20,weighted_df.loc['2020-05-31'].latitude - 1),
             fontsize=20,
             color='red')

plt.title("The geographic center of COVID-19 over time", fontsize = 30)

plt.axis('off')
plt.show();

In [ ]:
#Global cases
fig = plt.figure()
ax = plt.axes()

#ax.plot(x, np.sin(x));
#data
groupby_global = df.groupby('date').sum()
x = groupby_global.index
y = groupby_global.total_cases

#plot
ax.plot(x,y,c='r')
ax.bar(x,y)
ax.tick_params(axis='x',which='both',labelbottom=False)
ax.set_title('Global cases over time')
ax.set_xlabel("Date")
ax.set_ylabel("Cases")

#save figure
plt.savefig('/Users/sebastiangraff/Desktop/Data_Analysis/COVID19-Exploration/plot_images/global_cases.png')
plt.show();

In [ ]:
#Global cases vs deaths
fig, ax = plt.subplots(figsize = (15,5),nrows=1,ncols=2)

#data
groupby_global = df.groupby('date').sum()
x = groupby_global.index
y1 = groupby_global.total_cases
y2 = groupby_global.total_deaths

#plot
ax[0].plot(x,y1,c='purple',label='Cases')
ax[0].plot(x,y2,c='red',label='Deaths')
ax[0].tick_params(axis='x',which='both',labelbottom=False)
ax[0].set_title('Global cases over time')
ax[0].set_xlabel("Date")
ax[0].set_ylabel("Cases")

ax[1].plot(x,y1,c='purple',label='Cases')
ax[1].plot(x,y2,c='red',label='Deaths')
ax[1].tick_params(axis='x',which='both',labelbottom=False)
ax[1].set_title('Global logarithimic cases over time,')
ax[1].set_xlabel("Date")
ax[1].set_ylabel("Cases")
ax[1].set_yscale('log')

#save figure
ax[0].legend()
ax[1].legend()
plt.savefig('/Users/sebastiangraff/Desktop/Data_Analysis/COVID19-Exploration/plot_images/global_cases_vs_deaths.png')
plt.show();

In [ ]:
groupby_global = df.groupby('date').sum()
groupby_global

In [ ]:
#Global cases vs tests

#data
groupby_global = df.groupby('date').sum()
x = groupby_global.new_tests
y = groupby_global.new_cases

plt.scatter(x,y)
plt.title("COVID-19 Cases vs number of Tests")
plt.xlabel("Tests")
plt.ylabel("Cases")

plt.savefig('/Users/sebastiangraff/Desktop/Data_Analysis/COVID19-Exploration/plot_images/global_tests_vs_cases.png')
plt.show();

In [ ]:
#Stacked plot by continents

#data
groupby_continent = df.groupby('continent').sum()
x=df.date
y=df.total_cases[df.continent ==]
 
# Basic stacked area chart.
plt.stackplot(x,y, labels=df.continent.unique())
plt.legend(loc='upper left')

In [ ]:
from collections import defaultdict

#Data
continent_dict=defaultdict(list)
for index, row in df.iterrows():
    continent_dict[row.continent].append(row.total_cases)

x=df.date
y1=continent_dict['North America']
y2=continent_dict['Asia']
y3=continent_dict['Africa']
y4=continent_dict['Europa']
y5=continent_dict['South America']
y6=continent_dict['Australia']
 
# Plot
plt.stackplot(continent_dict.keys(), y1,y2, labels=continent_dict.keys())
plt.legend(loc='upper left')
plt.show();

#np.array(d.keys(),dtype=float)